openapi: 3.0.3
info:
  title: Store API
  description: Simple API to create and update store informations
  version: 2.0.1
servers:
  - url: /
paths:
  /stores:
    get:
      operationId: app.list
      parameters:
        - in: query
          name: storeAddress
          schema:
            type: string
        - in: query
          name: limit
          schema:
            default: 100
            format: int32
            minimum: 0
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  stores:
                    items:
                      allOf:
                        - $ref: '#/components/schemas/ResumeStore'
                    type: array
                type: object
          description: Return stores
      summary: List Stores
      tags:
        - Stores
    post:
      operationId: app.create
      parameters:
        - in: query
          name: storeId
          required: true
          schema:
            format: int32
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Store'
        required: true
      responses:
        '201':
          content: {}
          description: Store created
      summary: Create a Store
      tags:
        - Stores
      x-codegen-request-body-name: store
  '/store/{storeId}':
    get:
      operationId: app.detail
      parameters:
        - in: path
          name: storeId
          required: true
          schema:
            format: int32
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Store'
          description: Return store
        '404':
          content: {}
          description: Store does not exist
      summary: Detail of a Store
      tags:
        - Stores
    put:
      operationId: app.update
      parameters:
        - in: path
          name: storeId
          required: true
          schema:
            format: int32
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Store'
        required: false
      responses:
        '200':
          content: {}
          description: Store updated
      summary: Update a Store
      tags:
        - Stores
      x-codegen-request-body-name: store
    delete:
      operationId: app.remove
      parameters:
        - in: path
          name: storeId
          required: true
          schema:
            format: int32
            type: integer
      responses:
        '204':
          content: {}
          description: Store was deleted
        '404':
          content: {}
          description: Store does not exist
      summary: Remove a Store
      tags:
        - Stores
components:
  parameters:
    storeId:
      in: path
      name: storeId
      required: true
      schema:
        format: int32
        type: integer
  requestBodies:
    storeBody:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Store'
      required: false
  schemas:
    ResumeStore:
      properties:
        id:
          description: store identifier
          format: int32
          type: integer
        name:
          description: Store name
          example: Apple Park Visitor Center
          maxLength: 100
          minLength: 1
          type: string
      type: object
    Store:
      properties:
        address:
          description: Coordinates of the store
          example: '37.3327° N, 122.0053° W'
          minLength: 1
          type: string
        created:
          description: Creation time
          example: '2017-11-17T15:49:51.230000+02:00'
          format: date-time
          readOnly: true
          type: string
        id:
          description: store identifier
          format: int32
          type: integer
        name:
          description: Store name
          example: Apple Park Visitor Center
          maxLength: 100
          minLength: 1
          type: string
        tags:
          description: Custom tags
          items:
            type: string
          type: array
      required:
        - name
      type: object
