swagger: '2.0'
info:
  title: Shop API
  version: "0.1"
  description: Simple API to create and update store informations
consumes:
  - application/json
produces:
  - application/json
paths:
  /stores:
    get:
      tags: [Stores]
      operationId: app.get_stores
      summary: Get all stores
      parameters:
        - name: store_address
          in: query
          type: string
        - name: limit
          in: query
          type: integer
          format: int32
          minimum: 0
          default: 100
      responses:
        200:
          description: Return stores
          schema:
            type: object
            properties:
              pets:
                type: array
                items:
                  $ref: '#/definitions/Store'
  /store/{store_name}:
    get:
      tags: [Stores]
      operationId: app.get_store
      summary: Get a specific store
      parameters:
        - $ref: '#/parameters/store_name'
      responses:
        200:
          description: Return pet
          schema:
            $ref: '#/definitions/Store'
        404:
          description: Store does not exist
    put:
      tags: [Stores]
      operationId: app.put_store
      summary: Create or update a store
      parameters:
        - $ref: '#/parameters/store_name'
        - name: store
          in: body
          schema:
            $ref: '#/definitions/Store'
      responses:
        200:
          description: Store updated
        201:
          description: New store created
    delete:
      tags: [Stores]
      operationId: app.delete_store
      summary: Remove a store
      parameters:
        - $ref: '#/parameters/store_name'
      responses:
        204:
          description: Store was deleted
        404:
          description: Store does not exist


parameters:
  store_name:
    name: store_name
    description: Store Unique identifier
    in: path
    type: string
    required: true

definitions:
  Store:
    type: object
    required:
      - name
      - store_address
    properties:
      name:
        type: string
        description: Store's name
        example: "Apple Park Visitor Center"
        minLength: 1
        maxLength: 100
      store_address:
        type: string
        description: Coordinates of the store
        example: "37.3327° N, 122.0053° W"
        minLength: 1
      tags:
        type: object
        description: Custom tags
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2017-11-17T15:49:51.230+02:00"
