consumes:
  - application/json
definitions:
  ResumeStore:
    properties:
      id:
        description: store identifier
        format: int32
        type: integer
      name:
        description: Store's name
        example: Apple Park Visitor Center
        maxLength: 100
        minLength: 1
        type: string
    type: object
  Store:
    properties:
      address:
        description: Coordinates of the store
        example: '37.3327° N, 122.0053° W'
        minLength: 1
        type: string
      created:
        description: Creation time
        example: '2017-11-17T13:49:51.230Z'
        format: date-time
        type: string
      id:
        description: store identifier
        format: int32
        type: integer
        readOnly: true
      name:
        description: Store's name
        example: Apple Park Visitor Center
        maxLength: 100
        minLength: 1
        type: string
      tags:
        description: Custom tags
        items:
          type: string
        type: array
    required:
      - name
    type: object
info:
  description: Simple API to create and update store informations
  title: Store API
  version: 2.2.1
paths:
  '/stores/{storeId}':
    delete:
      operationId: app.remove
      parameters:
        - format: int32
          in: path
          name: storeId
          required: true
          type: integer
      responses:
        '204':
          description: Store was deleted
        '404':
          description: Store does not exist
      summary: Remove a Store
      tags:
        - '2. Store API - Detail, Update and Remove'
    get:
      operationId: app.detail
      parameters:
        - format: int32
          in: path
          name: storeId
          required: true
          type: integer
      responses:
        '200':
          description: Return store
          schema:
            $ref: '#/definitions/Store'
        '404':
          description: Store does not exist
      summary: Detail of a Store
      tags:
        - '2. Store API - Detail, Update and Remove'
    put:
      operationId: app.update
      parameters:
        - format: int32
          in: path
          name: storeId
          required: true
          type: integer
        - in: body
          name: store
          required: false
          schema:
            $ref: '#/definitions/Store'
            x-scope:
              - ''
      responses:
        '200':
          description: Store updated
        '404':
          description: Store does not exist
      summary: Update a Store
      tags:
        - '2. Store API - Detail, Update and Remove'
      x-codegen-request-body-name: store
  /stores:
    get:
      operationId: app.list
      parameters:
        - in: query
          name: storeAddress
          type: string
        - default: 100
          format: int32
          in: query
          name: limit
          type: integer
      responses:
        '200':
          description: Return stores
          schema:
            properties:
              stores:
                items:
                  $ref: '#/definitions/ResumeStore'
                  x-scope:
                    - ''
                type: array
            type: object
      summary: List Stores
      tags:
        - 1. Store API - List and Create
    post:
      operationId: app.create
      parameters:
        - in: body
          name: store
          required: true
          schema:
            $ref: '#/definitions/Store'
            x-scope:
              - ''
      responses:
        '201':
          description: Store created
        '400':
          description: Store already exist
      summary: Create a Store
      tags:
        - 1. Store API - List and Create
      x-codegen-request-body-name: store
produces:
  - application/json
swagger: '2.0'
x-components:
  parameters:
    storeId:
      in: path
      name: storeId
      required: true
      schema:
        format: int32
        type: integer
  requestBodies:
    storeBody:
      content:
        application/json:
          schema:
            $ref: '#/definitions/Store'
      required: false

