swagger: '2.0'
info:
  title: Store API
  description: Simple API to create and update store informations
  version: '2.2.1'
consumes:
  - application/json
produces:
  - application/json
paths:
  /stores:
    get:
      tags:
        - '1. Store API - List and Create'
      summary: List Stores
      operationId: app.list
      parameters:
        - name: storeAddress
          in: query
          type: string
        - name: limit
          in: query
          format: int32
          default: 100
          type: integer
      responses:
        '200':
          description: Return stores
          schema:
            type: object
            properties:
              stores:
                type: array
                items:
                  $ref: '#/definitions/ResumeStore'
    post:
      tags:
        - '1. Store API - List and Create'
      summary: Create a Store
      operationId: app.create
      parameters:
        - name: storeId
          in: query
          required: true
          format: int32
          type: integer
        - required: true
          name: store
          in: body
          schema:
            $ref: '#/definitions/Store'
      responses:
        '201':
          description: Store created
        '400':
          description: Store already exist
      x-codegen-request-body-name: store
    
  '/store/{storeId}':
    get:
      tags:
        - '2. Store API - Detail, Update and Remove'
      summary: Detail of a Store
      operationId: app.detail
      parameters:
        - name: storeId
          in: path
          required: true
          format: int32
          type: integer
      responses:
        '200':
          description: Return store
          schema:
            $ref: '#/definitions/Store'
        '404':
          description: Store does not exist
    put:
      tags:
        - '2. Store API - Detail, Update and Remove'
      summary: Update a Store
      operationId: app.update
      parameters:
        - name: storeId
          in: path
          required: true
          format: int32
          type: integer
        - required: false
          name: store
          in: body
          schema:
            $ref: '#/definitions/Store'
      responses:
        '200':
          description: Store updated
        '404':
          description: Store does not exist
      x-codegen-request-body-name: store
    delete:
      tags:
        - '2. Store API - Detail, Update and Remove'
      summary: Remove a Store
      operationId: app.remove
      parameters:
        - name: storeId
          in: path
          required: true
          format: int32
          type: integer
      responses:
        '204':
          description: Store was deleted
        '404':
          description: Store does not exist
definitions:
  ResumeStore:
    type: object
    properties:
      id:
        type: integer
        description: store identifier
        format: int32
      name:
        maxLength: 100
        minLength: 1
        type: string
        description: Store's name
        example: Apple Park Visitor Center
  Store:
    required:
      - name
    type: object
    properties:
      id:
        type: integer
        description: store identifier
        format: int32
      name:
        maxLength: 100
        minLength: 1
        type: string
        description: Store's name
        example: Apple Park Visitor Center
      address:
        minLength: 1
        type: string
        description: Coordinates of the store
        example: '37.3327° N, 122.0053° W'
      tags:
        type: array
        description: Custom tags
        items:
          type: string
      created:
        type: string
        format: date-time
        description: Creation time
        example: '2017-11-17T13:49:51.230Z'
x-components:
  parameters:
    storeId:
      name: storeId
      in: path
      required: true
      schema:
        type: integer
        format: int32
  requestBodies:
    storeBody:
      content:
        application/json:
          schema:
            $ref: '#/definitions/Store'
      required: false
